"""
Google Drive API client.

Thin wrapper around Drive API v3 for the folder-picker feature:
  - list_folders()  — list all folders the user has access to (optionally under a parent)
  - search_folders() — name-based search
  - get_folder_metadata() — fetch a single folder's metadata
  - list_files_in_folder() — list files inside a selected folder (used later by sync)
  - upload_as_google_doc() — upload a .docx and convert it to a Google Doc in Drive

Auth model:
The caller passes a `token_data` dict (same shape as the one stored on
UserEmailConnection.token_data — {token, refresh_token, scopes, expiry}).
We reuse the refresh helper from google_docs.py so token refresh logic
lives in one place.

Scopes required:
  - drive.readonly  — read/download files (template fetch, indexing)
  - drive.file      — create/upload files generated by Zippy (MOM, NDA, drafts)
Both are requested as part of PERSONAL_OAUTH_SCOPES during the Gmail OAuth flow.
"""
from __future__ import annotations

import json
import logging
from typing import Any, Optional

import httpx

from app.clients.google_docs import DRIVE_SCOPE, _refresh_token_if_needed

logger = logging.getLogger(__name__)

DRIVE_API_BASE = "https://www.googleapis.com/drive/v3"
DRIVE_UPLOAD_BASE = "https://www.googleapis.com/upload/drive/v3"
FOLDER_MIME = "application/vnd.google-apps.folder"
SHORTCUT_MIME = "application/vnd.google-apps.shortcut"
DRIVE_FILE_SCOPE = "https://www.googleapis.com/auth/drive.file"
GDOC_MIME = "application/vnd.google-apps.document"
DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"


def _has_drive_scope(token_data: dict) -> bool:
    scopes = token_data.get("scopes", [])
    if isinstance(scopes, list):
        return any(DRIVE_SCOPE in scope for scope in scopes)
    return DRIVE_SCOPE in str(scopes)


def _has_drive_write_scope(token_data: dict) -> bool:
    """True if the token has drive.file or full drive scope (allows creating files)."""
    scopes = token_data.get("scopes", [])
    scope_str = " ".join(scopes) if isinstance(scopes, list) else str(scopes)
    return DRIVE_FILE_SCOPE in scope_str or "auth/drive " in scope_str or scope_str.endswith("auth/drive")


async def _ensure_token(
    token_data: dict,
    client_id: str,
    client_secret: str,
) -> tuple[str, dict]:
    """Refresh the token if needed. Returns (access_token, updated_token_data)."""
    if not _has_drive_scope(token_data):
        raise PermissionError(
            "Token does not include drive.readonly scope — user must reconnect Gmail."
        )
    updated = await _refresh_token_if_needed(token_data, client_id, client_secret)
    access_token = updated.get("token")
    if not access_token:
        raise ValueError("Failed to obtain a valid access token for Drive API")
    return access_token, updated


async def upload_as_google_doc(
    *,
    filename: str,
    docx_bytes: bytes,
    token_data: dict,
    client_id: str,
    client_secret: str,
    parent_folder_id: Optional[str] = None,
) -> tuple[str, str]:
    """Upload a .docx file to Drive and convert it to a Google Doc.

    Uses a multipart upload with ``mimeType = application/vnd.google-apps.document``
    so Drive converts the Word content automatically.

    Returns ``(drive_file_id, webViewLink)`` on success.
    Raises ``PermissionError`` if the token lacks drive.file scope (user needs
    to reconnect Gmail so the new scope is granted).
    """
    if not _has_drive_write_scope(token_data):
        raise PermissionError(
            "Token does not include drive.file scope. "
            "The user must reconnect Google in Settings to grant Zippy "
            "permission to create files in Drive."
        )

    access_token, _ = await _ensure_token(token_data, client_id, client_secret)

    metadata: dict[str, Any] = {
        "name": filename,
        "mimeType": GDOC_MIME,  # tells Drive to convert the uploaded .docx
    }
    if parent_folder_id:
        metadata["parents"] = [parent_folder_id]

    boundary = "zippy_mp_boundary_x9k2"
    meta_bytes = json.dumps(metadata).encode()

    # Multipart body: metadata part + file bytes part
    body = (
        f"--{boundary}\r\n"
        f"Content-Type: application/json; charset=UTF-8\r\n\r\n"
    ).encode()
    body += meta_bytes
    body += f"\r\n--{boundary}\r\n".encode()
    body += f"Content-Type: {DOCX_MIME}\r\n\r\n".encode()
    body += docx_bytes
    body += f"\r\n--{boundary}--".encode()

    async with httpx.AsyncClient(timeout=60) as http:
        resp = await http.post(
            f"{DRIVE_UPLOAD_BASE}/files",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type": f"multipart/related; boundary={boundary}",
            },
            params={
                "uploadType": "multipart",
                "fields": "id,webViewLink",
                "supportsAllDrives": "true",
            },
            content=body,
        )

    if resp.status_code not in (200, 201):
        raise RuntimeError(
            f"Drive upload failed (HTTP {resp.status_code}): {resp.text[:400]}"
        )

    data = resp.json()
    file_id = data.get("id", "")
    web_view_link = data.get("webViewLink", "")
    logger.info("Zippy doc uploaded to Drive: file_id=%s url=%s", file_id, web_view_link)
    return file_id, web_view_link


async def upload_as_google_sheet(
    *,
    filename: str,
    docx_bytes: bytes,
    token_data: dict,
    client_id: str,
    client_secret: str,
    parent_folder_id: Optional[str] = None,
) -> tuple[str, str]:
    """Upload an .xlsx to Drive and convert it to a native Google Sheet.

    Identical multipart pattern to ``upload_as_google_doc`` — only the
    target mimeType (``application/vnd.google-apps.spreadsheet``) and the
    file part Content-Type (the .xlsx mime) differ. We keep both helpers
    rather than parameterizing because the target type is the whole point
    of the function name; callers pick the right one.

    The parameter is still called ``docx_bytes`` for signature symmetry with
    ``upload_as_google_doc`` — it carries arbitrary file bytes (here, .xlsx).
    """
    if not _has_drive_write_scope(token_data):
        raise PermissionError(
            "Token does not include drive.file scope. "
            "The user must reconnect Google in Settings to grant Zippy "
            "permission to create files in Drive."
        )

    access_token, _ = await _ensure_token(token_data, client_id, client_secret)

    sheet_mime = "application/vnd.google-apps.spreadsheet"
    xlsx_mime = (
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

    metadata: dict[str, Any] = {
        "name": filename,
        "mimeType": sheet_mime,  # tells Drive to convert the uploaded .xlsx
    }
    if parent_folder_id:
        metadata["parents"] = [parent_folder_id]

    boundary = "zippy_mp_boundary_x9k2"
    meta_bytes = json.dumps(metadata).encode()

    body = (
        f"--{boundary}\r\n"
        f"Content-Type: application/json; charset=UTF-8\r\n\r\n"
    ).encode()
    body += meta_bytes
    body += f"\r\n--{boundary}\r\n".encode()
    body += f"Content-Type: {xlsx_mime}\r\n\r\n".encode()
    body += docx_bytes
    body += f"\r\n--{boundary}--".encode()

    async with httpx.AsyncClient(timeout=60) as http:
        resp = await http.post(
            f"{DRIVE_UPLOAD_BASE}/files",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type": f"multipart/related; boundary={boundary}",
            },
            params={
                "uploadType": "multipart",
                "fields": "id,webViewLink",
                "supportsAllDrives": "true",
            },
            content=body,
        )

    if resp.status_code not in (200, 201):
        raise RuntimeError(
            f"Drive upload failed (HTTP {resp.status_code}): {resp.text[:400]}"
        )

    data = resp.json()
    file_id = data.get("id", "")
    web_view_link = data.get("webViewLink", "")
    logger.info("ROI sheet uploaded to Drive: file_id=%s url=%s", file_id, web_view_link)
    return file_id, web_view_link


async def upload_as_google_slides(
    *,
    filename: str,
    docx_bytes: bytes,
    token_data: dict,
    client_id: str,
    client_secret: str,
    parent_folder_id: Optional[str] = None,
) -> tuple[str, str]:
    """Upload a .pptx to Drive and convert it to a native Google Slides deck.

    Same multipart pattern as ``upload_as_google_doc`` and
    ``upload_as_google_sheet`` — only the target mimeType
    (``application/vnd.google-apps.presentation``) and the file part
    Content-Type (.pptx mime) differ. Parameter is still called
    ``docx_bytes`` for signature symmetry; it carries .pptx bytes here.
    """
    if not _has_drive_write_scope(token_data):
        raise PermissionError(
            "Token does not include drive.file scope. "
            "The user must reconnect Google in Settings to grant Zippy "
            "permission to create files in Drive."
        )

    access_token, _ = await _ensure_token(token_data, client_id, client_secret)

    slides_mime = "application/vnd.google-apps.presentation"
    pptx_mime = (
        "application/vnd.openxmlformats-officedocument."
        "presentationml.presentation"
    )

    metadata: dict[str, Any] = {
        "name": filename,
        "mimeType": slides_mime,  # tells Drive to convert the uploaded .pptx
    }
    if parent_folder_id:
        metadata["parents"] = [parent_folder_id]

    boundary = "zippy_mp_boundary_x9k2"
    meta_bytes = json.dumps(metadata).encode()

    body = (
        f"--{boundary}\r\n"
        f"Content-Type: application/json; charset=UTF-8\r\n\r\n"
    ).encode()
    body += meta_bytes
    body += f"\r\n--{boundary}\r\n".encode()
    body += f"Content-Type: {pptx_mime}\r\n\r\n".encode()
    body += docx_bytes
    body += f"\r\n--{boundary}--".encode()

    async with httpx.AsyncClient(timeout=60) as http:
        resp = await http.post(
            f"{DRIVE_UPLOAD_BASE}/files",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type": f"multipart/related; boundary={boundary}",
            },
            params={
                "uploadType": "multipart",
                "fields": "id,webViewLink",
                "supportsAllDrives": "true",
            },
            content=body,
        )

    if resp.status_code not in (200, 201):
        raise RuntimeError(
            f"Drive upload failed (HTTP {resp.status_code}): {resp.text[:400]}"
        )

    data = resp.json()
    file_id = data.get("id", "")
    web_view_link = data.get("webViewLink", "")
    logger.info(
        "Zippy slides uploaded to Drive: file_id=%s url=%s",
        file_id, web_view_link,
    )
    return file_id, web_view_link


async def list_folders(
    *,
    token_data: dict,
    client_id: str,
    client_secret: str,
    parent_id: Optional[str] = None,
    page_size: int = 100,
    include_shared: bool = True,
) -> tuple[list[dict[str, Any]], dict]:
    """
    List Drive folders the user can access.

    Args:
        parent_id: If set, only returns folders directly inside this folder.
                   If None, returns top-level folders (under My Drive root + shared).
        include_shared: Include folders shared with the user (not just owned).

    Returns:
        (folders, updated_token_data)

    Each folder dict contains: id, name, parents, modifiedTime, ownedByMe, shared.
    """
    access_token, updated_token = await _ensure_token(token_data, client_id, client_secret)

    # Build the q query. Drive API v3 query syntax:
    #   mimeType = folder                OR  mimeType = shortcut    — real folders + shortcuts
    #   trashed  = false                                             — ignore trashed
    #   '<parent_id>' in parents                                     — direct children
    #
    # We include shortcuts so folders that live under shared-drives / team-
    # folders and are exposed via shortcuts aren't invisible to the picker.
    # Shortcut targets are resolved below via shortcutDetails.
    mime_clause = f"(mimeType='{FOLDER_MIME}' or mimeType='{SHORTCUT_MIME}')"
    q_parts = [mime_clause, "trashed=false"]
    if parent_id:
        q_parts.append(f"'{parent_id}' in parents")
    q = " and ".join(q_parts)

    params = {
        "q": q,
        "pageSize": page_size,
        "fields": (
            "nextPageToken, files(id, name, parents, modifiedTime, ownedByMe, "
            "shared, driveId, mimeType, shortcutDetails)"
        ),
        "orderBy": "name",
        "supportsAllDrives": "true",
        "includeItemsFromAllDrives": "true" if include_shared else "false",
        "corpora": "allDrives" if include_shared else "user",
    }

    folders: list[dict[str, Any]] = []
    async with httpx.AsyncClient(timeout=20) as http:
        page_token: Optional[str] = None
        while True:
            if page_token:
                params["pageToken"] = page_token
            resp = await http.get(
                f"{DRIVE_API_BASE}/files",
                headers={"Authorization": f"Bearer {access_token}"},
                params=params,
            )
            resp.raise_for_status()
            data = resp.json() or {}
            folders.extend(data.get("files", []))
            page_token = data.get("nextPageToken")
            if not page_token:
                break
            # Safety: don't fetch more than a few thousand folders per call.
            if len(folders) >= 1000:
                break

    # Normalize: keep only items that represent folders (real or shortcut-to-folder).
    # For shortcuts we rewrite `id` to the target folder's id so downstream
    # drilling-in and recursive walks hit the real folder.
    normalized: list[dict[str, Any]] = []
    for f in folders:
        mime = f.get("mimeType")
        if mime == FOLDER_MIME:
            normalized.append(f)
        elif mime == SHORTCUT_MIME:
            sd = f.get("shortcutDetails") or {}
            if sd.get("targetMimeType") == FOLDER_MIME and sd.get("targetId"):
                f["id"] = sd["targetId"]
                normalized.append(f)
            # else: shortcut to a non-folder — skip (the picker only lists folders).

    return normalized, updated_token


async def search_folders(
    *,
    query: str,
    token_data: dict,
    client_id: str,
    client_secret: str,
    page_size: int = 50,
) -> tuple[list[dict[str, Any]], dict]:
    """Search for folders by name (case-insensitive contains match)."""
    access_token, updated_token = await _ensure_token(token_data, client_id, client_secret)

    safe_query = (query or "").replace("'", "\\'").strip()
    if not safe_query:
        return [], updated_token

    q = (
        f"mimeType='{FOLDER_MIME}' and trashed=false and name contains '{safe_query}'"
    )
    params = {
        "q": q,
        "pageSize": page_size,
        "fields": "files(id, name, parents, modifiedTime, ownedByMe, shared, driveId)",
        "orderBy": "name",
        "supportsAllDrives": "true",
        "includeItemsFromAllDrives": "true",
        "corpora": "allDrives",
    }

    async with httpx.AsyncClient(timeout=20) as http:
        resp = await http.get(
            f"{DRIVE_API_BASE}/files",
            headers={"Authorization": f"Bearer {access_token}"},
            params=params,
        )
        resp.raise_for_status()
        data = resp.json() or {}
        return data.get("files", []), updated_token


async def get_folder_metadata(
    *,
    folder_id: str,
    token_data: dict,
    client_id: str,
    client_secret: str,
) -> tuple[Optional[dict[str, Any]], dict]:
    """Fetch metadata for a single folder by ID. Returns None if not found / no access."""
    access_token, updated_token = await _ensure_token(token_data, client_id, client_secret)

    params = {
        "fields": "id, name, parents, modifiedTime, ownedByMe, shared, driveId, mimeType",
        "supportsAllDrives": "true",
    }
    async with httpx.AsyncClient(timeout=20) as http:
        resp = await http.get(
            f"{DRIVE_API_BASE}/files/{folder_id}",
            headers={"Authorization": f"Bearer {access_token}"},
            params=params,
        )
        if resp.status_code in {403, 404}:
            return None, updated_token
        resp.raise_for_status()
        meta = resp.json() or {}

    if meta.get("mimeType") != FOLDER_MIME:
        # The ID points to something, but not a folder.
        return None, updated_token
    return meta, updated_token


async def list_files_in_folder_recursive(
    *,
    folder_id: str,
    token_data: dict,
    client_id: str,
    client_secret: str,
    max_files: int = 2000,
) -> tuple[list[dict[str, Any]], dict]:
    """
    Walk a folder recursively, returning every non-folder file beneath it.

    Drive's API doesn't have a "descendants" filter, so we do a BFS: fetch
    direct children, queue the sub-folders, repeat. Stops once ``max_files``
    is reached to protect against pathological trees.
    """
    visited: set[str] = set()
    queue: list[str] = [folder_id]
    files: list[dict[str, Any]] = []
    updated = token_data

    while queue and len(files) < max_files:
        current = queue.pop(0)
        if current in visited:
            continue
        visited.add(current)

        # Direct files (non-folder) in this folder
        batch_files, updated = await list_files_in_folder(
            folder_id=current,
            token_data=updated,
            client_id=client_id,
            client_secret=client_secret,
            max_files=max_files - len(files),
        )
        files.extend(batch_files)

        # Sub-folders to traverse next
        sub_folders, updated = await list_folders(
            token_data=updated,
            client_id=client_id,
            client_secret=client_secret,
            parent_id=current,
        )
        for sub in sub_folders:
            if sub.get("id") and sub["id"] not in visited:
                queue.append(sub["id"])

    return files[:max_files], updated


# MIME-type → export format for Google native docs. We bias toward formats
# pdfplumber/python-docx can handle downstream without extra tooling.
GOOGLE_EXPORT_MAP = {
    "application/vnd.google-apps.document": (
        "text/plain",
        ".txt",
    ),
    "application/vnd.google-apps.spreadsheet": (
        "text/csv",
        ".csv",
    ),
    "application/vnd.google-apps.presentation": (
        "text/plain",
        ".txt",
    ),
}


async def download_file_bytes(
    *,
    file_id: str,
    mime_type: str,
    token_data: dict,
    client_id: str,
    client_secret: str,
) -> tuple[Optional[bytes], str, dict]:
    """
    Download a Drive file's bytes for indexing.

    Returns ``(bytes, effective_mime_type, updated_token)``. For Google-native
    files we export to a plain format; for normal files we use ``alt=media``.
    ``bytes`` is None if the file can't be fetched (e.g. 403, empty).
    """
    access_token, updated_token = await _ensure_token(token_data, client_id, client_secret)

    export = GOOGLE_EXPORT_MAP.get(mime_type)
    async with httpx.AsyncClient(timeout=60) as http:
        if export is not None:
            export_mime, _ = export
            resp = await http.get(
                f"{DRIVE_API_BASE}/files/{file_id}/export",
                headers={"Authorization": f"Bearer {access_token}"},
                params={"mimeType": export_mime},
            )
            effective = export_mime
        else:
            resp = await http.get(
                f"{DRIVE_API_BASE}/files/{file_id}",
                headers={"Authorization": f"Bearer {access_token}"},
                params={"alt": "media", "supportsAllDrives": "true"},
            )
            effective = mime_type

        if resp.status_code in {403, 404}:
            logger.info("Drive file %s returned %s — skipping", file_id, resp.status_code)
            return None, effective, updated_token
        resp.raise_for_status()
        return resp.content, effective, updated_token


async def list_files_in_folder(
    *,
    folder_id: str,
    token_data: dict,
    client_id: str,
    client_secret: str,
    page_size: int = 100,
    max_files: int = 500,
) -> tuple[list[dict[str, Any]], dict]:
    """
    List non-folder files directly inside a folder.

    Used later by the sync task that ingests Drive content into the CRM.
    """
    access_token, updated_token = await _ensure_token(token_data, client_id, client_secret)

    # Exclude sub-folders (they're walked separately by the recursive caller)
    # but INCLUDE shortcuts — some Drive layouts expose files only via
    # shortcuts under shared/team folders, so skipping them would drop
    # real content from the index.
    q = (
        f"'{folder_id}' in parents and trashed=false "
        f"and mimeType != '{FOLDER_MIME}'"
    )
    params = {
        "q": q,
        "pageSize": page_size,
        "fields": (
            "nextPageToken, files(id, name, mimeType, modifiedTime, size, "
            "webViewLink, shortcutDetails)"
        ),
        "orderBy": "modifiedTime desc",
        "supportsAllDrives": "true",
        "includeItemsFromAllDrives": "true",
    }

    files: list[dict[str, Any]] = []
    async with httpx.AsyncClient(timeout=20) as http:
        page_token: Optional[str] = None
        while True:
            if page_token:
                params["pageToken"] = page_token
            resp = await http.get(
                f"{DRIVE_API_BASE}/files",
                headers={"Authorization": f"Bearer {access_token}"},
                params=params,
            )
            resp.raise_for_status()
            data = resp.json() or {}
            files.extend(data.get("files", []))
            page_token = data.get("nextPageToken")
            if not page_token or len(files) >= max_files:
                break

    # Resolve file shortcuts → real file id + mimeType so the downloader
    # fetches the target, not the shortcut stub.
    resolved: list[dict[str, Any]] = []
    for f in files:
        if f.get("mimeType") == SHORTCUT_MIME:
            sd = f.get("shortcutDetails") or {}
            target_id = sd.get("targetId")
            target_mime = sd.get("targetMimeType")
            if not target_id or target_mime == FOLDER_MIME:
                # Skip shortcuts that point nowhere, or to folders (handled by folder walker).
                continue
            f["id"] = target_id
            f["mimeType"] = target_mime or f["mimeType"]
        resolved.append(f)

    return resolved[:max_files], updated_token
