apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beacon.fullname" . }}-frontend
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
    {{- include "beacon.selectorLabels" (dict "context" . "component" "frontend") | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "beacon.selectorLabels" (dict "context" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beacon.selectorLabels" (dict "context" . "component" "frontend") | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ include "beacon.image" (dict "image" .Values.frontend.image "global" .Values.global) }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
