{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beacon.fullname" . }}-redis
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
    {{- include "beacon.selectorLabels" (dict "context" . "component" "redis") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "beacon.selectorLabels" (dict "context" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beacon.selectorLabels" (dict "context" . "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
