"""Generic Markdown-ish → DOCX converter for ad-hoc Zippy outputs.

Zippy can be asked for all sorts of deliverables ("draft a follow-up email",
"write a one-pager on X"). We parse lightweight markdown and emit a clean
``.docx`` — good enough for first drafts that the user can polish.
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from docx import Document
from docx.shared import Pt, RGBColor

from app.clients.google_drive import upload_as_google_doc
from app.config import settings
from app.database import AsyncSessionLocal as async_session
from app.services.zippy_docs.base import (
    GeneratedDocument,
    build_output_path,
)

logger = logging.getLogger(__name__)


@dataclass
class GenericDocInput:
    title: str
    markdown: str
    client_name: Optional[str] = None


_HEADING_RE = re.compile(r"^(#{1,3})\s+(.*)$")
_BULLET_RE = re.compile(r"^[-*•]\s+(.*)$")
_NUMBERED_RE = re.compile(r"^\d+[.)]\s+(.*)$")


def _render(data: GenericDocInput, path) -> None:
    doc = Document()
    title = doc.add_heading(data.title or "Zippy Draft", level=0)
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x17, 0x4A, 0x8B)

    if data.client_name:
        sub = doc.add_paragraph()
        sub_run = sub.add_run(f"Prepared for {data.client_name}")
        sub_run.italic = True
        sub_run.font.size = Pt(10)

    for raw in (data.markdown or "").splitlines():
        line = raw.rstrip()
        if not line.strip():
            doc.add_paragraph()
            continue
        heading_match = _HEADING_RE.match(line)
        if heading_match:
            level = min(3, len(heading_match.group(1)))
            h = doc.add_heading(heading_match.group(2).strip(), level=level)
            for run in h.runs:
                run.font.color.rgb = RGBColor(0x17, 0x4A, 0x8B)
            continue
        bullet_match = _BULLET_RE.match(line)
        if bullet_match:
            doc.add_paragraph(bullet_match.group(1).strip(), style="List Bullet")
            continue
        numbered_match = _NUMBERED_RE.match(line)
        if numbered_match:
            doc.add_paragraph(numbered_match.group(1).strip(), style="List Number")
            continue
        doc.add_paragraph(line)

    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        f"\nGenerated by Zippy on {datetime.utcnow().strftime('%d %b %Y %H:%M UTC')}"
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(0x8A, 0x8A, 0x8A)

    doc.save(str(path))


async def generate(data: GenericDocInput, user_id: Optional[str] = None) -> GeneratedDocument:
    safe_slug = data.client_name or data.title or "draft"
    path, url = build_output_path("draft", safe_slug)
    _render(data, path)
    result = GeneratedDocument(
        filename=path.name,
        path=str(path),
        url=url,
        kind="generic_docx",
        summary=f"Draft created: {data.title or path.name}",
        created_at=datetime.utcnow(),
    )

    # Upload to Google Drive as an editable Google Doc.
    await _try_upload_to_drive(result, path, data.title or safe_slug, user_id=user_id)
    return result


async def _try_upload_to_drive(
    doc: GeneratedDocument,
    path,
    label: str,
    *,
    user_id: Optional[str],
) -> None:
    """Upload the generated .docx to the user's Drive folder as a Google Doc."""
    if doc.drive_url:
        return
    if user_id:
        from app.services.zippy_docs.base import (
            cache_upload,
            get_cached_upload,
        )
        cached = get_cached_upload(str(user_id), label, doc.kind)
        if cached:
            doc.drive_url = cached
            logger.info("Reusing cached generic Drive upload: %s", cached)
            return
    try:
        from sqlalchemy import or_
        from sqlalchemy import case as sa_case
        from app.models.user_email_connection import UserEmailConnection
        from sqlmodel import select as sm_select

        async with async_session() as session:
            stmt = sm_select(UserEmailConnection).where(
                UserEmailConnection.is_active == True,  # noqa: E712
            )
            if user_id is not None:
                stmt = stmt.where(
                    or_(
                        UserEmailConnection.user_id == user_id,
                        UserEmailConnection.is_admin_folder == True,  # noqa: E712
                    )
                )
                priority = sa_case(
                    (UserEmailConnection.user_id == user_id, 0), else_=1
                )
                stmt = stmt.order_by(priority)
            result = await session.execute(stmt.limit(1))
            connection = result.scalar_one_or_none()

        if not connection:
            logger.info("No active Drive connection — skipping Google Docs upload for generic doc")
            return

        docx_bytes = path.read_bytes()
        gdoc_name = f"{label} — {doc.created_at.strftime('%d %b %Y')}"
        folder_id = connection.selected_drive_folder_id or None

        file_id, web_view_link = await upload_as_google_doc(
            filename=gdoc_name,
            docx_bytes=docx_bytes,
            token_data=connection.token_data,
            client_id=settings.gmail_client_id,
            client_secret=settings.gmail_client_secret,
            parent_folder_id=folder_id,
        )
        doc.drive_file_id = file_id
        doc.drive_url = web_view_link
        logger.info("Generic doc uploaded to Google Docs: %s", web_view_link)
        if user_id and web_view_link:
            from app.services.zippy_docs.base import cache_upload
            cache_upload(str(user_id), label, doc.kind, web_view_link)
    except PermissionError as exc:
        logger.info("drive.file scope not yet granted — skipping upload: %s", exc)
    except Exception as exc:
        logger.warning("Google Docs upload failed (non-fatal): %s", exc)
