"""Generic Markdown-ish → DOCX converter for ad-hoc Zippy outputs.

Zippy can be asked for all sorts of deliverables ("draft a follow-up email",
"write a one-pager on X"). We parse lightweight markdown and emit a clean
``.docx`` — good enough for first drafts that the user can polish.
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from docx import Document
from docx.shared import Pt, RGBColor

from app.services.zippy_docs.base import (
    GeneratedDocument,
    build_output_path,
)

logger = logging.getLogger(__name__)


@dataclass
class GenericDocInput:
    title: str
    markdown: str
    client_name: Optional[str] = None


_HEADING_RE = re.compile(r"^(#{1,3})\s+(.*)$")
_BULLET_RE = re.compile(r"^[-*•]\s+(.*)$")
_NUMBERED_RE = re.compile(r"^\d+[.)]\s+(.*)$")


def _render(data: GenericDocInput, path) -> None:
    doc = Document()
    title = doc.add_heading(data.title or "Zippy Draft", level=0)
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x17, 0x4A, 0x8B)

    if data.client_name:
        sub = doc.add_paragraph()
        sub_run = sub.add_run(f"Prepared for {data.client_name}")
        sub_run.italic = True
        sub_run.font.size = Pt(10)

    for raw in (data.markdown or "").splitlines():
        line = raw.rstrip()
        if not line.strip():
            doc.add_paragraph()
            continue
        heading_match = _HEADING_RE.match(line)
        if heading_match:
            level = min(3, len(heading_match.group(1)))
            h = doc.add_heading(heading_match.group(2).strip(), level=level)
            for run in h.runs:
                run.font.color.rgb = RGBColor(0x17, 0x4A, 0x8B)
            continue
        bullet_match = _BULLET_RE.match(line)
        if bullet_match:
            doc.add_paragraph(bullet_match.group(1).strip(), style="List Bullet")
            continue
        numbered_match = _NUMBERED_RE.match(line)
        if numbered_match:
            doc.add_paragraph(numbered_match.group(1).strip(), style="List Number")
            continue
        doc.add_paragraph(line)

    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        f"\nGenerated by Zippy on {datetime.utcnow().strftime('%d %b %Y %H:%M UTC')}"
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(0x8A, 0x8A, 0x8A)

    doc.save(str(path))


async def generate(data: GenericDocInput) -> GeneratedDocument:
    safe_slug = data.client_name or data.title or "draft"
    path, url = build_output_path("draft", safe_slug)
    _render(data, path)
    return GeneratedDocument(
        filename=path.name,
        path=str(path),
        url=url,
        kind="generic_docx",
        summary=f"Draft created: {data.title or path.name}",
        created_at=datetime.utcnow(),
    )
